server:
  port: 8080

spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

minio:
  endpoint: http://localhost:9000
  access-key-id: OkO5ultaxqbpguBclVJH
  access-key-secret: gJqIlO224ZcEM0fx53oSjT8cKW3VL3VVSpcPedEk